version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11

  pre_build:
    commands:
      - ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)

  build:
    commands:
      - |
        aws deploy create-deployment-group \
          --application-name dev-CodeDeployApp \
          --deployment-group-name dev-dg \
          --service-role-arn arn:aws:iam::$ACCOUNT_ID:role/dev-CodeDeployRole \
          --deployment-style deploymentType=BLUE_GREEN,deploymentOption=WITH_TRAFFIC_CONTROL \
          --auto-scaling-groups dev-app-asg \
          --load-balancer-info targetGroupInfoList=[{name=dev-tg-blue}] \
          --blue-green-deployment-configuration terminateBlueInstancesOnDeploymentSuccess={action=TERMINATE,terminationWaitTimeInMinutes=1},deploymentReadyOption={actionOnTimeout=CONTINUE_DEPLOYMENT},greenFleetProvisioningOption={action=COPY_AUTO_SCALING_GROUP} \
          --deployment-config-name CodeDeployDefault.AllAtOnce \
          --region us-east-1
      - |     
        aws deploy create-deployment-group \
          --application-name dev-CodeDeployApp \
          --deployment-group-name dev-dg \
          --service-role-arn arn:aws:iam::$ACCOUNT_ID:role/dev-CodeDeployRole \
          --deployment-style deploymentType=BLUE_GREEN,deploymentOption=WITH_TRAFFIC_CONTROL \
          --auto-scaling-groups dev-app-asg \
          --load-balancer-info targetGroupInfoList=[{name=dev-tg-blue}] \
          --blue-green-deployment-configuration terminateBlueInstancesOnDeploymentSuccess={action=TERMINATE,terminationWaitTimeInMinutes=1},deploymentReadyOption={actionOnTimeout=CONTINUE_DEPLOYMENT},greenFleetProvisioningOption={action=COPY_AUTO_SCALING_GROUP} \
          --deployment-config-name CodeDeployDefault.AllAtOnce \
          --region us-west-1

artifacts:
  files:
    - '**/*'
